### ISSUE TITLE
use it in Docusaurus v2,not working, show error below

### ISSUE THREAD

**Issue by jarlin8** [su-pa/Wikipedia-preview-boxes#1]
Uncaught TypeError: Cannot read properties of null (reading 'insertAdjacentHTML')
    at wikiPreviewBox.min.js:6:209

this is docsite: https://wikidoc.pages.dev/

thanks

**Comment by su-pa** [comment]
**Either** insert the code snippet `<script src="https://su-pa.net/wikiPrevBox/wikiPreviewBox.min.js"></script>` right before the `</body>` (at the very end of your web page and not inside `<head></head>)` and it will work. 

**Or alternatively,** just add `defer` to the code snippet: 
`<script src="https://su-pa.net/wikiPrevBox/wikiPreviewBox.min.js" defer></script>` 
and it will also work if the snippet is inside `<head></head>`  (where it is currently on your web page)
